version: "4"
services: 
  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - db
    restart: 
      always
  db: 
    image: postgres:15.1
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111111 
      POSTGRES_DB: codica_test
    ports:
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgres/data
volumes: 
  db-data:               